#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: f35655a
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kteatime
Version  : 24.08.0
Release  : 72
URL      : https://download.kde.org/stable/release-service/24.08.0/src/kteatime-24.08.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.08.0/src/kteatime-24.08.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.08.0/src/kteatime-24.08.0.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GFDL-1.2 GPL-2.0
Requires: kteatime-bin = %{version}-%{release}
Requires: kteatime-data = %{version}-%{release}
Requires: kteatime-license = %{version}-%{release}
Requires: kteatime-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : ki18n-dev
BuildRequires : knotifications-dev
BuildRequires : knotifyconfig-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package bin
Summary: bin components for the kteatime package.
Group: Binaries
Requires: kteatime-data = %{version}-%{release}
Requires: kteatime-license = %{version}-%{release}

%description bin
bin components for the kteatime package.


%package data
Summary: data components for the kteatime package.
Group: Data

%description data
data components for the kteatime package.


%package doc
Summary: doc components for the kteatime package.
Group: Documentation

%description doc
doc components for the kteatime package.


%package license
Summary: license components for the kteatime package.
Group: Default

%description license
license components for the kteatime package.


%package locales
Summary: locales components for the kteatime package.
Group: Default

%description locales
locales components for the kteatime package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kteatime-24.08.0
cd %{_builddir}/kteatime-24.08.0
pushd ..
cp -a kteatime-24.08.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724438252
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1724438252
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kteatime
cp %{_builddir}/kteatime-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kteatime/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kteatime-%{version}/LICENSES/GFDL-1.2-or-later.txt %{buildroot}/usr/share/package-licenses/kteatime/ee03d68f6be20b170e5ea5d114d6acafb3f2d1dc || :
cp %{_builddir}/kteatime-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kteatime/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kteatime
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/kteatime
/usr/bin/kteatime

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kteatime.desktop
/usr/share/icons/hicolor/16x16/apps/kteatime.png
/usr/share/icons/hicolor/22x22/apps/kteatime.png
/usr/share/icons/hicolor/32x32/apps/kteatime.png
/usr/share/icons/hicolor/48x48/apps/kteatime.png
/usr/share/icons/hicolor/64x64/apps/kteatime.png
/usr/share/icons/hicolor/scalable/apps/kteatime.svgz
/usr/share/knotifications6/kteatime.notifyrc
/usr/share/metainfo/org.kde.kteatime.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kteatime/index.cache.bz2
/usr/share/doc/HTML/ca/kteatime/index.docbook
/usr/share/doc/HTML/de/kteatime/config.png
/usr/share/doc/HTML/de/kteatime/index.cache.bz2
/usr/share/doc/HTML/de/kteatime/index.docbook
/usr/share/doc/HTML/en/kteatime/config.png
/usr/share/doc/HTML/en/kteatime/index.cache.bz2
/usr/share/doc/HTML/en/kteatime/index.docbook
/usr/share/doc/HTML/es/kteatime/index.cache.bz2
/usr/share/doc/HTML/es/kteatime/index.docbook
/usr/share/doc/HTML/fr/kteatime/config.png
/usr/share/doc/HTML/fr/kteatime/index.cache.bz2
/usr/share/doc/HTML/fr/kteatime/index.docbook
/usr/share/doc/HTML/it/kteatime/index.cache.bz2
/usr/share/doc/HTML/it/kteatime/index.docbook
/usr/share/doc/HTML/nl/kteatime/index.cache.bz2
/usr/share/doc/HTML/nl/kteatime/index.docbook
/usr/share/doc/HTML/pt/kteatime/index.cache.bz2
/usr/share/doc/HTML/pt/kteatime/index.docbook
/usr/share/doc/HTML/pt_BR/kteatime/config.png
/usr/share/doc/HTML/pt_BR/kteatime/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kteatime/index.docbook
/usr/share/doc/HTML/ru/kteatime/index.cache.bz2
/usr/share/doc/HTML/ru/kteatime/index.docbook
/usr/share/doc/HTML/sv/kteatime/config.png
/usr/share/doc/HTML/sv/kteatime/index.cache.bz2
/usr/share/doc/HTML/sv/kteatime/index.docbook
/usr/share/doc/HTML/tr/kteatime/index.cache.bz2
/usr/share/doc/HTML/tr/kteatime/index.docbook
/usr/share/doc/HTML/uk/kteatime/config.png
/usr/share/doc/HTML/uk/kteatime/index.cache.bz2
/usr/share/doc/HTML/uk/kteatime/index.docbook

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kteatime/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/kteatime/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kteatime/ee03d68f6be20b170e5ea5d114d6acafb3f2d1dc

%files locales -f kteatime.lang
%defattr(-,root,root,-)

